// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiewpresyoxvdftknohz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZXdwcmVzeW94dmRmdGtub2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTU3MDQsImV4cCI6MjA3MjQ3MTcwNH0.pwF4wkK4Cjgp9kVgYp9X1aXKhTyAxrZFaHkps1NhqTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});